### ISSUE TITLE
Home page table with minimal key info for the report server

### ISSUE THREAD

**Issue by OmkarSaMo** [matinnuhamunada/bgcflow_wrapper_prototype#3]
### Home page overview table

If it's easy, it would be nice to add a table on the main home page of reports with a list of each project and key statistics of that project. 

- Number of genomes
- Number of average BGCs
- Number of GCFs
- Number of GCFs with known BGCs
- Number of GCFs that are unique (singletons)
- Number of genes in core genome 
- Number of genes in pangenome

**Comment by matinnuhamunada** [comment]
I believe this has been resolved through another approach. The command is now `bgcflow serve`.
Repo moved to NBChub.
