### ISSUE TITLE
Error in address of correct rule json file

### ISSUE THREAD

**Issue by OmkarSaMo** [matinnuhamunada/bgcflow_wrapper_prototype#6]
https://github.com/matinnuhamunada/bgcflow_wrapper/blob/034de9f33184ada3ca51748e2b9f89e4dd7c5313/bgcflow_wrapper/projects_util.py#L70

I believe this should now be updated from `"workflow/rules/rules.json"` to `"workflow/rules/rules_main.json"`

**Comment by matinnuhamunada** [comment]
This should be corrected. The repo moved to NBChub.
